### PR TITLE
Assorted fixes.

### PR DESCRIPTION
**Pull request by KDPRoss**
- Change activation arg to milliseconds; allow 0 delay. (Move my tab *now*!)

- Change 'arrage' -> 'arrange' in assorted places.

- Restyle code to favour lambdas, single-tick strings, destructuring, and brevity.

- Adjust some comments.

### CODE REVIEW

**Comment by smallStall** [comment]
I have merged. I will put it up on marketplace later.

**Comment by KDPRoss** [comment]
> I have merged. I will put it up on marketplace later.

Brilliant! Love the extension -- it's made my life just a little bit better :~}

**Comment by KDPRoss** [comment]
@smallStall Oh, just thought of this: I know very little about actually publishing extensions ... but maybe you should increase the version number to `0.5.0`? Didn't make any difference locally when I was testing, so I didn't touch that!

**Comment by smallStall** [comment]
@KDPRoss 
Thanks for letting me know.
I have increased the version to 0.5.0 and  put it up on marketplace!

**Pull request merged**
